.\" Manpage for beluga-cli
.\" Report errors or typos at https://www.github.com/entrez/beluga-cli/issues
.\" Copyright 2018, 2019 Michael Meyer <michael@vitormedia.com>
.TH beluga-cli 1 "20 Mar 2019" "0.7.0" "Beluga CLI Manual"
.SH NAME
beluga-cli \- manipulate files on an origin server and BelugaCDN
.SH SYNOPSIS
\fBbeluga-cli\fR <\fIcommand\fR> [<\fIflags\fR>]... [<\fIarguments\fR>]
[\fB--profile=\fR<\fIprofilename\fR>]
.SH DESCRIPTION
\fBbeluga-cli\fR is a bash utility which uses
.I curl(1)
- with the exception of the ftp command, which uses
.I ftp(1)
- to manipulate files on an FTP origin server (like the one provided by Beluga) and interact
with the BelugaCDN API <https://www.belugacdn.com/>. It can be used to quickly and easily
accomplish, and/or as a step in the automation of, many tasks involving the management of
objects which fit one or both of these criteria.
.SH COMMANDS
.SS File Manipulation
.TP 8
.B cp
Copy a file to, from, or within the origin, resulting in duplicate copies at the source and
destination.
.br
usage: \fBbeluga-cli cp\fR [\fB-ips\fR] <\fIlocalpath\fR> <cdn://\fIuri\fR> or <cdn://\fIuri\fR>
<\fIlocalpath\fR> or <cdn://\fIuri\fR> <\fIcdn://uri\fR>
.TP
.B mv
Move a file to, from, or within the server, so that the original copy is deleted and only the new
one at the destination is kept.
.br
usage: \fBbeluga-cli mv\fR [\fB-ips\fR] <\fIlocalpath\fR> <cdn://\fIuri\fR> or <cdn://\fIuri\fR>
<\fIlocalpath\fR> or <cdn://\fIuri\fR> <cdn://\fIuri\fR>
.TP
.B rm
Delete a remote file or directory.
.br
usage: \fBbeluga-cli rm\fR [\fB-irs\fR] <cdn://\fIuri\fR>
.TP
.B mkdir
Create a new directory on the origin server.
.br
usage: \fBbeluga-cli mkdir\fR [\fB-ps\fR] <cdn://\fIuri\fR>
.SS Navigation and File Discovery
.TP 8
.B ftp
Log on to the origin server in an interactive ftp session.
.br
usage: \fBbeluga-cli ftp\fR
.TP
.B ls
Briefly list the contents of a directory.
.br
usage: \fBbeluga-cli ls\fR [\fB-s\fR] <cdn://\fIuri\fR>
.TP
.B ll
List the contents of a directory plus permissions, creation date, etc.
.br
usage: \fBbeluga-cli ll\fR [\fB-s\fR] <cdn://\fIuri\fR>
.SS CDN Utilities
.TP 8
.B iv
Invalidate a cached file on the CDN, forcing it to retrieve a fresh copy from the origin
server the next time it is needed.
.br
usage: \fBbeluga-cli iv\fR [\fB-s\fR] <cdn://\fIuri\fR>
.SS Internal Tools
.TP 8
.B update
Check whether the version of \fBbeluga-cli\fR running is the latest available; if a newer version
exists, the local copy of the script will be updated.
.br
usage: \fBbeluga-cli update\fR
.TP
.B help
Get help about a command, or display this page if no command is specified.
.br
usage: \fBbeluga-cli\fR [<\fIcommand\fR>] \fBhelp\fR
.TP
.B config
Set up origin server & CDN credentials and other information; see the ``configuration'' section
below for more details.
.br
usage: \fBbeluga-cli config\fR
.LP
Note that in all commands, remote/origin server URIs should be formatted as cdn://\fIpath\fR.
For instance, in order to download the file http://cdn.your.site/dir1/file.txt, you could run
the command
.LP
.RS 4
.B beluga-cli cp cdn://dir1/file.txt ~/Downloads
.RE
.LP
As a general rule, cdn://path/to/obj corresponds to http://cdn.your.site/path/to/obj.
.LP
.SH OPTIONS
.TP 8
.B -i
If a remote file may be modified by the specified command, \fBbeluga-cli\fR will request invalidation
of that uri after the operation is complete.
.TP
.B -p
Create all intermediate directories in the specified path (the destination path, when used with
mv or cp commands) as needed.
.TP
.B -r
Delete all contents of the specified directory recursively.
.TP
.B -s
The program will suppress output to stderr while maintaining normal output to stdout (e.g. the
directory listing generated by ls).
.TP
\fB--profile=\fR<\fIprofilename\fR>
Create and switch between any number of named profiles. May be useful, for example, if you
manage CDN operations and file hosting for multiple sites or applications through Beluga.
.LP
Many options can only be used on certain commands, as described in the usage information
under ``commands'' above. If an option is used on a command where it is not standard,
\fBbeluga-cli\fR will generally print an error message but then ignore the flag and continue.
.LP
.SH CONFIGURATION
.LP
In order to get everything working correctly before you start using \fBbeluga-cli\fR, you must run
the command \fBbeluga-cli config\fR to define the location and credentials used for your origin, the
credentials used for access to the Beluga API, and so on.
.LP
Note that the ``origin server location'' should include the entire path used as the origin on
BelugaCDN. If you entered an additional path in your property's settings page on your Beluga
dashboard, include it here. If you use Beluga's in-house origin solution, this may also include
a directory with your property name (e.g. X.X.X.X/cdn.your.site/).
.LP
Your origin server username and password will be stored & transmitted as plain text, so ensure
they are not used elsewhere.
.LP
On the other hand, although you will be prompted for your BelugaCDN username and password if
you choose to create a new token during the setup & configuration process, these are only used
once (for HTTP Basic authentication, i.e. transmitted in Base64) to generate the token, and are
not stored persistently anywhere.
.SH EXIT CODES
.IP 1
Failure; operation aborted.
.IP 2
Invalidation request already pending.
.IP 3
Malformed or illegal input.
.IP 4
Missing configuration files.
.IP 5
In a series of operations, only some were successful.
.SH CONTRIBUTION AND AVAILABILITY
To contribute, to report a bug, or to download the latest version of this software, visit:
.LP
.RS 4
.B https://www.github.com/entrez/beluga-cli
.RE
.SH AUTHOR
Written and maintained by Michael Meyer <\fImichael@vitormedia.com\fR>
.SH LICENSE AND COPYRIGHT
Copyright (c) 2018, 2019 Michael Meyer
.LP
Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:
.LP
The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.
.LP
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
